apiVersion: v1
kind: ConfigMap
metadata:
  name: licesnse-app-config
  labels:
    app: license-app
data:
  POSTGRES_DB: licensedb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123
  POSTGRES_DIALECT: org.hibernate.dialect.PostgreSQLDialect
  POSTGRES_DB_URL: jdbc:postgresql://localhost:5432